### ISSUE TITLE
文本没有正确地分开显示

### ISSUE THREAD

**Issue by Feryquitous** [crafteverywhere/Cultist-Simulator-Chinese-Localization-Issues-Tracker#4]
![image](https://user-images.githubusercontent.com/24260600/56455719-9ec38980-6327-11e9-8f22-860c18515716.png)

**Comment by crafteverywhere** [comment]
todo: 检查下格式符是否和原文一致。格式符前后可能需要留空格。

**Comment by Feryquitous** [comment]
应该是的，因为英文本也有类似的bug
